# Generated by Django 4.1.1 on 2022-09-26 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_bugs_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bugs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
