# Generated by Django 4.1.1 on 2022-09-30 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_bugs_created_at_bugs_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='assigned_to',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bugs',
            name='comments',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='priority',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='status',
            field=models.CharField(choices=[('Not being worked on', 'Not being worked on'), ('Work in Progress', 'Work in Progress'), ('Fixed', 'Fixed')], max_length=50),
        ),
    ]
