# Generated by Django 4.1.1 on 2022-09-30 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_bugs_assigned_to_alter_bugs_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugs',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='bugs',
            name='assigned_to',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
