# Generated by Django 4.1.1 on 2022-09-30 20:03

from django.conf import settings
from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_remove_bugs_assigned_to_bugs_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='assigned_to',
            field=models.ManyToManyField(default=main_app.models.defaultUser, to=settings.AUTH_USER_MODEL),
        ),
    ]
