# Generated by Django 4.1.1 on 2022-09-30 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_bugs_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugs',
            name='assigned_to',
        ),
    ]
