# Generated by Django 4.1.1 on 2022-09-30 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0007_remove_bugs_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='assigned_to',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
